# Generated by Django 3.0.3 on 2020-02-27 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200226_2329'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersocialnetwork',
            options={'verbose_name': "User's Social Network"},
        ),
    ]
