# Generated by Django 3.0.3 on 2020-02-27 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200227_0418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersocialnetwork',
            name='handle',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='usersocialnetwork',
            name='url',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
