# Generated by Django 3.0.3 on 2020-03-04 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20200304_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialnetwork',
            name='format',
            field=models.CharField(choices=[('handle', 'handle'), ('url', 'url')], default='handle', max_length=8),
            preserve_default=False,
        ),
    ]
