# Generated by Django 3.0.3 on 2020-03-04 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_socialnetwork_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersocialnetwork',
            name='identifer',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
