# Generated by Django 3.0.3 on 2020-03-04 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_usersocialnetwork_identifer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersocialnetwork',
            old_name='identifer',
            new_name='identifier',
        ),
        migrations.RemoveField(
            model_name='usersocialnetwork',
            name='handle',
        ),
        migrations.RemoveField(
            model_name='usersocialnetwork',
            name='url',
        ),
    ]
