# Generated by Django 3.0.3 on 2020-03-05 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20200304_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialnetwork',
            name='base_url',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
