# Generated by Django 3.0.3 on 2020-03-19 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_socialnetwork_base_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersocialnetwork',
            options={'ordering': ['socialnetwork'], 'verbose_name': "User's Social Network"},
        ),
    ]
