# Generated by Django 3.0.3 on 2020-03-19 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20200319_1853'),
    ]

    operations = [
        migrations.RunSQL("INSERT INTO accounts_source (name, description, url, created_at, updated_at) VALUES ('ioo.coop/directory/', 'The Internet of Ownership # PlatformCoop Directory', 'http://ioo.coop/directory/', '2020-02-14 19:51:46.888448', '2020-02-14 19:51:46.888448');"),
    ]
