# Generated by Django 3.0.3 on 2020-03-22 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20200320_1940'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['last_name']},
        ),
    ]
