# Generated by Django 3.0.3 on 2020-03-24 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialnetwork',
            name='font_awesome',
            field=models.TextField(blank=True, max_length=32),
        ),
    ]
