# Generated by Django 3.0.3 on 2020-03-24 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_socialnetwork_font_awesome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialnetwork',
            name='font_awesome',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
