# Generated by Django 3.0.3 on 2020-04-03 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_auto_20200327_2153'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('culture_code', models.CharField(max_length=7, primary_key=True, serialize=False, unique=True)),
                ('iso_name', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'ordering': ['culture_code'],
            },
        ),
    ]
