# Generated by Django 3.0.3 on 2020-04-03 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='languages',
            field=models.ManyToManyField(blank=True, null=True, to='accounts.Language'),
        ),
    ]
