# Generated by Django 3.0.3 on 2020-04-04 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_auto_20200404_0337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='languages',
            field=models.ManyToManyField(blank=True, to='mdi.Language'),
        ),
    ]
