# Generated by Django 3.0.3 on 2020-04-05 01:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdi', '0057_auto_20200405_0044'),
        ('accounts', '0027_auto_20200404_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='related_individuals',
            field=models.ManyToManyField(related_name='_user_related_individuals_+', through='mdi.EntitiesEntities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='related_organizations',
            field=models.ManyToManyField(through='mdi.EntitiesEntities', to='mdi.Organization'),
        ),
    ]
