# Generated by Django 3.0.3 on 2020-04-05 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdi', '0059_auto_20200405_0444'),
        ('accounts', '0028_auto_20200405_0104'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='services',
            field=models.ManyToManyField(blank=True, to='mdi.Service'),
        ),
    ]
