# Generated by Django 3.0.3 on 2020-04-06 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdi', '0059_auto_20200405_0444'),
        ('accounts', '0029_user_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='challenges',
            field=models.ManyToManyField(blank=True, to='mdi.Challenge'),
        ),
    ]
