# Generated by Django 3.0.3 on 2020-04-06 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_user_challenges'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='affiliation',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='field_of_study',
            field=models.TextField(blank=True, default=''),
        ),
    ]
