# Generated by Django 3.0.3 on 2020-04-06 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_auto_20200406_0207'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='projects',
            field=models.TextField(blank=True, default=''),
        ),
    ]
