# Generated by Django 3.0.3 on 2020-04-06 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_user_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='field_of_study',
            field=models.CharField(blank=True, default='', max_length=254),
        ),
    ]
