# Generated by Django 3.0.3 on 2020-04-06 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_auto_20200406_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='socialnetworks',
            field=models.ManyToManyField(blank=True, through='accounts.UserSocialNetwork', to='accounts.SocialNetwork'),
        ),
        migrations.AlterField(
            model_name='usersocialnetwork',
            name='identifier',
            field=models.CharField(max_length=255),
        ),
    ]
