# Generated by Django 3.0.3 on 2020-04-09 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_auto_20200407_0005'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(blank=True, to='accounts.Role'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='single_role', to='accounts.Role'),
        ),
    ]
