# Generated by Django 3.0.3 on 2020-04-09 14:55

from django.db import migrations, models
from django.contrib.auth import get_user_model

def forward(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    for user in User.objects.all():
        if user.role is not None:
            user.roles.add(user.role)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_auto_20200409_1524'),
    ]

    operations = [
        migrations.RunPython(forward)
    ]
