# Generated by Django 3.0.3 on 2020-06-09 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0042_user_has_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='community_skills',
            field=models.TextField(blank=True, default=''),
        ),
    ]
