# Generated by Django 3.0.3 on 2020-06-09 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0043_add_community_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='affiliation_url',
            field=models.URLField(blank=True, default='', max_length=255),
        ),
    ]
