# Generated by Django 3.0.3 on 2020-06-16 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0044_add_affiliation_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='icon',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
