# Generated by Django 3.0.3 on 2020-06-17 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0045_add_role_icon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socialnetwork',
            old_name='font_awesome',
            new_name='icon',
        ),
    ]
