# Generated by Django 3.0.7 on 2020-06-23 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mdi', '0081_alter_organization_to_use_mdi_source'),
        ('accounts', '0046_add_socialnetwork_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='source',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='mdi.Source'),
        ),
        migrations.DeleteModel(
            name='Source',
        ),
    ]
