# Generated by Django 3.0.3 on 2020-07-11 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0047_move_source_to_mdi_nd_drop'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contact_email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='Contact email'),
        ),
    ]
