from django.contrib.gis.db import models


class Ecosystem2020Questions(models.Model):
    column_name = models.CharField(max_length=2)
    question = models.CharField(max_length=254, blank=True,)

    class Meta:
        managed = False
        db_table = 'surveys_ecosystem2020_questions'


class Ecosystem2020(models.Model):
    a = models.DateTimeField(db_column='A', auto_now=True)
    b = models.CharField(db_column='B', max_length=254, blank=True,)  
    c = models.CharField(db_column='C', max_length=254, blank=True,)  
    d = models.CharField(db_column='D', max_length=254, blank=True,)  
    e = models.CharField(db_column='E', max_length=254, blank=True,)  
    f = models.CharField(db_column='F', max_length=254, blank=True,)  
    g = models.CharField(db_column='G', max_length=254, blank=True,)  
    h = models.CharField(db_column='H', max_length=254, blank=True,)  
    i = models.CharField(db_column='I', max_length=254, blank=True,)  
    j = models.CharField(db_column='J', max_length=254, blank=True,)  
    k = models.CharField(db_column='K', max_length=254, blank=True,)  
    l = models.CharField(db_column='L', max_length=254, blank=True,)  
    m = models.CharField(db_column='M', max_length=254, blank=True,)  
    n = models.CharField(db_column='N', max_length=254, blank=True,)  
    o = models.CharField(db_column='O', max_length=254, blank=True,)  
    p = models.CharField(db_column='P', max_length=254, blank=True,)  
    q = models.CharField(db_column='Q', max_length=254, blank=True,)  
    r = models.CharField(db_column='R', max_length=254, blank=True,)  
    s = models.CharField(db_column='S', max_length=254, blank=True,)  
    t = models.CharField(db_column='T', max_length=254, blank=True,)  
    u = models.CharField(db_column='U', max_length=254, blank=True,)  
    v = models.CharField(db_column='V', max_length=254, blank=True,)  
    w = models.CharField(db_column='W', max_length=254, blank=True,)  
    x = models.CharField(db_column='X', max_length=254, blank=True,)  
    y = models.CharField(db_column='Y', max_length=254, blank=True,)  
    z = models.CharField(db_column='Z', max_length=254, blank=True,)  
    aa = models.CharField(db_column='AA', max_length=254, blank=True,)  
    ab = models.CharField(db_column='AB', max_length=254, blank=True,)  
    ac = models.CharField(db_column='AC', max_length=254, blank=True,)  
    ad = models.CharField(db_column='AD', max_length=254, blank=True,)  
    ae = models.CharField(db_column='AE', max_length=254, blank=True,)  
    af = models.CharField(db_column='AF', max_length=254, blank=True,)  
    ag = models.CharField(db_column='AG', max_length=254, blank=True,)  
    ah = models.CharField(db_column='AH', max_length=254, blank=True,)  
    ai = models.CharField(db_column='AI', max_length=254, blank=True,)  
    aj = models.CharField(db_column='AJ', max_length=254, blank=True,)  
    ak = models.CharField(db_column='AK', max_length=254, blank=True,)  
    al = models.CharField(db_column='AL', max_length=254, blank=True,)  
    am = models.CharField(db_column='AM', max_length=254, blank=True,)  
    an = models.CharField(db_column='AN', max_length=254, blank=True,)  
    ao = models.CharField(db_column='AO', max_length=254, blank=True,)  
    ap = models.CharField(db_column='AP', max_length=254, blank=True,)  
    aq = models.CharField(db_column='AQ', max_length=254, blank=True,)  
    ar = models.CharField(db_column='AR', max_length=254, blank=True,)  
    as_field = models.CharField(db_column='AS', max_length=254, blank=True,)  # Field renamed because it was a Python reserved word.
    at = models.CharField(db_column='AT', max_length=254, blank=True,)  
    au = models.CharField(db_column='AU', max_length=254, blank=True,)  
    av = models.CharField(db_column='AV', max_length=254, blank=True,)  
    aw = models.CharField(db_column='AW', max_length=254, blank=True,)  
    ax = models.CharField(db_column='AX', max_length=254, blank=True,)  
    ay = models.CharField(db_column='AY', max_length=254, blank=True,)  
    az = models.CharField(db_column='AZ', max_length=254, blank=True,)  
    ba = models.CharField(db_column='BA', max_length=254, blank=True,)  
    bb = models.CharField(db_column='BB', max_length=254, blank=True,)  
    bc = models.CharField(db_column='BC', max_length=254, blank=True,)  
    bd = models.CharField(db_column='BD', max_length=254, blank=True,)  
    be = models.CharField(db_column='BE', max_length=254, blank=True,)  
    bf = models.CharField(db_column='BF', max_length=254, blank=True,)  
    bg = models.CharField(db_column='BG', max_length=254, blank=True,)  
    bh = models.CharField(db_column='BH', max_length=254, blank=True,)  
    bi = models.CharField(db_column='BI', max_length=254, blank=True,)  
    bj = models.CharField(db_column='BJ', max_length=254, blank=True,)  
    bk = models.CharField(db_column='BK', max_length=254, blank=True,)  
    bl = models.CharField(db_column='BL', max_length=254, blank=True,)  
    bm = models.CharField(db_column='BM', max_length=254, blank=True,)  
    bn = models.CharField(db_column='BN', max_length=254, blank=True,)  
    bo = models.CharField(db_column='BO', max_length=254, blank=True,)  
    bp = models.CharField(db_column='BP', max_length=254, blank=True,)  
    bq = models.CharField(db_column='BQ', max_length=254, blank=True,)  
    br = models.CharField(db_column='BR', max_length=254, blank=True,)  
    bs = models.CharField(db_column='BS', max_length=254, blank=True,)  
    bt = models.CharField(db_column='BT', max_length=254, blank=True,)  
    bu = models.CharField(db_column='BU', max_length=254, blank=True,)  
    bv = models.CharField(db_column='BV', max_length=254, blank=True,)  
    bw = models.CharField(db_column='BW', max_length=254, blank=True,)  
    bx = models.CharField(db_column='BX', max_length=254, blank=True,)  
    by = models.CharField(db_column='BY', max_length=254, blank=True,)  
    bz = models.CharField(db_column='BZ', max_length=254, blank=True,)  
    ca = models.CharField(db_column='CA', max_length=254, blank=True,)  
    cb = models.CharField(db_column='CB', max_length=254, blank=True,)  
    cc = models.CharField(db_column='CC', max_length=254, blank=True,)  
    cd = models.CharField(db_column='CD', max_length=254, blank=True,)  
    ce = models.CharField(db_column='CE', max_length=254, blank=True,)  

    class Meta:
        managed = True
        db_table = 'surveys_ecosystem2020'
