# Generated by Django 3.0.3 on 2020-05-08 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecosystem2020',
            name='bg',
            field=models.TextField(blank=True),
        ),
    ]
