# Generated by Django 3.0.2 on 2020-01-17 19:41

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('postal_code', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=3)),
                ('email', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(null=True, srid=4326)),
            ],
        ),
    ]
