# Generated by Django 3.0.2 on 2020-01-17 20:00

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='lat',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='lng',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='email',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='organization',
            name='postal_code',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='state',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='url',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
