# Generated by Django 3.0.2 on 2020-01-17 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdi', '0002_auto_20200117_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
