# Generated by Django 3.0.3 on 2020-02-14 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mdi', '0004_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='source',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='mdi.Source'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='source',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='source',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='url',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
