# Generated by Django 3.0.3 on 2020-02-26 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mdi', '0005_auto_20200214_2003'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationSocialNetworks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handle', models.CharField(max_length=64)),
                ('url', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mdi.Organization')),
                ('socialnetwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mdi.SocialNetwork')),
            ],
        ),
        migrations.AddField(
            model_name='organization',
            name='socialnetworks',
            field=models.ManyToManyField(through='mdi.OrganizationSocialNetworks', to='mdi.SocialNetwork'),
        ),
    ]
