# Generated by Django 3.0.3 on 2020-02-27 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200226_2329'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('mdi', '0006_auto_20200226_1840'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationSocialNetwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handle', models.CharField(max_length=64)),
                ('url', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mdi.Organization')),
                ('socialnetwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.SocialNetwork')),
            ],
        ),
        migrations.DeleteModel(
            name='OrganizationSocialNetworks',
        ),
        migrations.DeleteModel(
            name='SocialNetwork',
        ),
        migrations.AlterField(
            model_name='organization',
            name='socialnetworks',
            field=models.ManyToManyField(through='mdi.OrganizationSocialNetwork', to='accounts.SocialNetwork'),
        ),
    ]
