# Generated by Django 3.0.2 on 2020-01-21 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mdi', '0007_auto_20200117_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='category',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='mdi.Category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mdi.Type'),
            preserve_default=False,
        ),
    ]
