# Generated by Django 3.0.3 on 2020-02-27 05:43

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mdi', '0008_auto_20200227_0418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
