# Generated by Django 3.0.2 on 2020-01-28 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdi', '0008_auto_20200121_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='activities',
            field=models.ManyToManyField(to='mdi.Activity'),
        ),
    ]
