# Generated by Django 3.0.3 on 2020-02-27 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdi', '0015_auto_20200227_2252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='license',
            name='languages_supported',
        ),
        migrations.AddField(
            model_name='tool',
            name='languages_supported',
            field=models.ManyToManyField(to='mdi.Language'),
        ),
    ]
