# Generated by Django 3.0.3 on 2020-02-28 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdi', '0018_auto_20200228_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='culture_code',
            field=models.CharField(max_length=7, unique=True),
        ),
        migrations.AlterField(
            model_name='language',
            name='iso_name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
