# Generated by Django 3.0.3 on 2020-02-28 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mdi', '0020_auto_20200228_1624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tool',
            name='languages_supported',
        ),
        migrations.DeleteModel(
            name='Language',
        ),
    ]
