# Generated by Django 3.0.3 on 2020-02-28 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdi', '0025_tool_pricing'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
