# Generated by Django 3.0.3 on 2020-03-02 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mdi', '0026_tool_notes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Activity',
            new_name='Sector',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='activities',
            new_name='sectors',
        ),
    ]
