# Generated by Django 3.0.3 on 2020-03-04 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdi', '0028_organization_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationsocialnetwork',
            name='identifier',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
