# Generated by Django 3.0.3 on 2020-03-04 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mdi', '0029_organizationsocialnetwork_identifier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationsocialnetwork',
            name='handle',
        ),
        migrations.RemoveField(
            model_name='organizationsocialnetwork',
            name='url',
        ),
    ]
