# Generated by Django 3.0.3 on 2020-03-19 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdi', '0030_auto_20200304_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='admin_email',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='founded',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='num_workers',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
