# Generated by Django 3.0.3 on 2020-03-19 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20200319_1909'),
        ('mdi', '0031_auto_20200319_0521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Source'),
        ),
        migrations.DeleteModel(
            name='Source',
        ),
    ]
