# Generated by Django 3.0.3 on 2020-03-22 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mdi', '0034_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Role',
        ),
    ]
