# Generated by Django 3.0.3 on 2020-03-22 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdi', '0035_delete_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='sectors',
            field=models.ManyToManyField(blank=True, null=True, to='mdi.Sector'),
        ),
    ]
