# Generated by Django 3.0.3 on 2020-03-24 03:31

from django.db import models, migrations


def forward(apps, schema_editor):
    Organization = apps.get_model("mdi", "Organization")
    for organization in Organization.objects.all():
        if organization.category is not None:
            organization.categories.add(organization.category)


class Migration(migrations.Migration):

    dependencies = [
        ('mdi', '0038_auto_20200324_0329'),
    ]

    operations = [
        migrations.RunPython(forward)
]
