# Generated by Django 3.0.3 on 2020-03-24 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mdi', '0039_auto_20200324_0331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='category',
        ),
    ]
