# Generated by Django 3.0.3 on 2020-03-25 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdi', '0041_auto_20200325_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='founded',
            field=models.DateField(blank=True, null=True),
        ),
    ]
