# Generated by Django 3.0.3 on 2020-03-25 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdi', '0042_auto_20200325_0121'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='organization',
            name='legal_status',
            field=models.ManyToManyField(blank=True, null=True, to='mdi.LegalStatus'),
        ),
    ]
