# Generated by Django 3.0.3 on 2020-03-25 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdi', '0043_auto_20200325_1800'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['order'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='legalstatus',
            options={'ordering': ['order'], 'verbose_name_plural': 'Legal Statuses'},
        ),
        migrations.AddField(
            model_name='legalstatus',
            name='order',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
