# Generated by Django 3.0.3 on 2020-03-25 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mdi', '0045_auto_20200325_1821'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Challenges',
            new_name='Challenge',
        ),
    ]
