# Generated by Django 3.0.3 on 2020-03-27 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdi', '0046_auto_20200325_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='logo_url',
            field=models.URLField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='organization',
            name='media_url',
            field=models.URLField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='license',
            name='url',
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='organization',
            name='admin_email',
            field=models.EmailField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='organization',
            name='email',
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name='organization',
            name='url',
            field=models.URLField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='tool',
            name='url',
            field=models.URLField(max_length=255),
        ),
    ]
