# Generated by Django 3.0.3 on 2020-03-31 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdi', '0048_auto_20200331_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='languages_supported',
            field=models.ManyToManyField(blank=True, null=True, to='mdi.Language'),
        ),
    ]
