# Generated by Django 3.0.3 on 2020-04-04 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mdi', '0051_auto_20200404_2304'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrganizationsUsers',
        ),
    ]
