# Generated by Django 3.0.3 on 2020-04-05 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdi', '0052_delete_organizationsusers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationship',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
