# Generated by Django 3.0.3 on 2020-04-05 00:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mdi', '0053_auto_20200405_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entitiesentities',
            name='from_ind',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_ind_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='entitiesentities',
            name='from_org',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_org_set', to='mdi.Organization'),
        ),
        migrations.AlterField(
            model_name='entitiesentities',
            name='relationship',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='mdi.Relationship'),
        ),
        migrations.AlterField(
            model_name='entitiesentities',
            name='to_ind',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_ind_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='entitiesentities',
            name='to_org',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_org_set', to='mdi.Organization'),
        ),
    ]
