# Generated by Django 3.0.3 on 2020-04-05 00:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mdi', '0056_auto_20200405_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='related_individuals',
            field=models.ManyToManyField(through='mdi.EntitiesEntities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organization',
            name='related_organizations',
            field=models.ManyToManyField(related_name='_organization_related_organizations_+', through='mdi.EntitiesEntities', to='mdi.Organization'),
        ),
    ]
