# Generated by Django 3.0.3 on 2020-04-05 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdi', '0057_auto_20200405_0044'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('order', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ['iso_name']},
        ),
    ]
