# Generated by Django 3.0.3 on 2020-04-05 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdi', '0058_auto_20200405_0443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
