# Generated by Django 3.0.3 on 2020-04-24 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdi', '0060_auto_20200409_0147'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='tools',
            field=models.ManyToManyField(blank=True, to='mdi.Tool'),
        ),
    ]
