# Generated by Django 3.0.3 on 2020-05-05 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mdi', '0061_organization_tools'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='stage',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='mdi.Stage'),
        ),
    ]
