# Generated by Django 3.0.3 on 2020-05-08 00:28

import django.contrib.postgres.fields.ranges
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mdi', '0062_auto_20200505_0225'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeographicScope',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(blank=True, choices=[(0, 'Local'), (1, 'Regional'), (2, 'National'), (3, 'International')], max_length=8)),
                ('city', models.CharField(blank=True, default='', max_length=255)),
                ('region', models.CharField(blank=True, default='', max_length=255)),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='organization',
            name='code_availability',
            field=models.CharField(blank=True, choices=[(0, 'Yes'), (1, 'Partially'), (2, 'No')], max_length=8),
        ),
        migrations.AddField(
            model_name='organization',
            name='impacted_exact_number',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='impacted_range',
            field=django.contrib.postgres.fields.ranges.IntegerRangeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='geographic_scope',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mdi.GeographicScope'),
        ),
    ]
