# Generated by Django 3.0.3 on 2020-05-08 02:46

import django.contrib.postgres.fields.ranges
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdi', '0063_auto_20200508_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geographicscope',
            name='scope',
            field=models.CharField(blank=True, choices=[(0, 'Local'), (1, 'Regional'), (2, 'National'), (3, 'International')], max_length=16),
        ),
        migrations.AlterField(
            model_name='organization',
            name='impacted_range',
            field=django.contrib.postgres.fields.ranges.IntegerRangeField(blank=True, default=None, null=True),
        ),
    ]
