# Generated by Django 3.0.3 on 2020-05-08 03:54

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mdi', '0064_auto_20200508_0246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='geographic_scope',
        ),
        migrations.AddField(
            model_name='organization',
            name='geo_scope',
            field=models.CharField(blank=True, choices=[(0, 'Local'), (1, 'Regional'), (2, 'National'), (3, 'International')], max_length=16),
        ),
        migrations.AddField(
            model_name='organization',
            name='geo_scope_city',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='organization',
            name='geo_scope_country',
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='organization',
            name='geo_scope_region',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.DeleteModel(
            name='GeographicScope',
        ),
    ]
