# Generated by Django 3.0.3 on 2020-05-17 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdi', '0066_auto_20200511_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='code_availability',
            field=models.CharField(blank=True, choices=[(0, 'Yes'), (1, 'Partially'), (2, 'No')], max_length=9),
        ),
    ]
