# Generated by Django 3.0.3 on 2020-05-25 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdi', '0068_survey_to_models_manytomany'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tool',
            name='sectors',
        ),
        migrations.AddField(
            model_name='tool',
            name='coop_made',
            field=models.BooleanField(default=False, verbose_name='Made by a cooperative'),
        ),
    ]
