# Generated by Django 3.0.3 on 2020-05-25 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mdi', '0069_add_coop_made'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tool',
            name='sectors',
        ),
    ]
