# Generated by Django 3.0.3 on 2020-05-28 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdi', '0070_add_tool_license_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='languages',
            field=models.ManyToManyField(blank=True, to='mdi.Language', verbose_name='Operating language'),
        ),
    ]
