# Generated by Django 3.0.3 on 2020-06-01 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdi', '0073_add_worker_distribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='num_members',
            field=models.IntegerField(blank=True, null=True, verbose_name='Number of members'),
        ),
    ]
