# Generated by Django 3.0.3 on 2020-06-12 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdi', '0074_add_number_of_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='code_availability',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('Partially', 'Partially'), ('No', 'No')], max_length=9),
        ),
    ]
