# Generated by Django 3.0.3 on 2020-06-12 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdi', '0075_update_code_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='geo_scope',
            field=models.CharField(blank=True, choices=[('Local', 'Local'), ('Regional', 'Regional'), ('National', 'National'), ('International', 'International')], max_length=16, verbose_name='Geographic scope'),
        ),
    ]
