# Generated by Django 3.0.3 on 2020-06-15 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdi', '0076_update_geo_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_group',
            field=models.CharField(choices=[('cooperatives', 'Cooperatives'), ('potential-cooperatives', 'Potential cooperatives'), ('other-organizations', 'Other organizations')], default='cooperatives', max_length=64, verbose_name='Category group'),
        ),
    ]
