# Generated by Django 3.0.3 on 2020-06-16 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdi', '0077_add_category_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_group',
            field=models.CharField(choices=[('cooperative', 'Cooperative'), ('potential-cooperative', 'Potential cooperative'), ('shared-platform', 'Shared platform'), ('supporting-organization', 'Supporting organization')], default='cooperative', max_length=64, verbose_name='Category group'),
        ),
    ]
