# Generated by Django 3.0.7 on 2020-06-23 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mdi', '0080_truncate_and_fill_mdi_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mdi.Source'),
        ),
    ]
