# Generated by Django 3.0.3 on 2020-06-24 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdi', '0082_add_code_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='icon',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
