# Generated by Django 3.0.3 on 2020-06-26 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdi', '0083_add_type_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='coop_made',
            field=models.CharField(blank=True, choices=[('', 'Not sure'), ('yes', 'Yes'), ('no', 'No')], default='', max_length=16, verbose_name='Made by a cooperative'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='license_type',
            field=models.CharField(blank=True, choices=[('', 'Not sure'), ('proprietary', 'Proprietary'), ('proprietary-with-floss-integration-tools', 'Proprietary with free / libre / open source integration tools'), ('floss', 'Free / libre / open source')], default='', max_length=64, verbose_name='License type'),
        ),
    ]
