# Generated by Django 3.0.3 on 2020-06-25 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdi', '0083_add_type_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='coop_made',
            field=models.CharField(choices=[('unknown', 'Not sure'), ('yes', 'Yes'), ('no', 'No')], default=0, max_length=16, verbose_name='Was this tool created by a co-op?'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Max 270 characters.', verbose_name='Description of tool'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='languages_supported',
            field=models.ManyToManyField(blank=True, to='mdi.Language', verbose_name='What languages does this tool support'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name of tool'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='url',
            field=models.URLField(max_length=255, verbose_name='URL of tool website'),
        ),
    ]
