# Generated by Django 3.0.3 on 2020-06-26 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdi', '0084_alter_tool_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='submitted_by_email',
            field=models.EmailField(default='', max_length=255),
        ),
    ]
