name: Run lint

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Cache node modules
      uses: actions/cache@v1
      with:
        path: node_modules
        key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
    - name: npm install and test
      run: |
        npm install
        npm test
      env:
        CI: true
    - name: Python Code Quality and Lint
      uses: ricardochaves/python-lint@v1.1.0
      with:
        python-root-list: "maps mdi"  
        use-pycodestyle: true
        use-pylint: false
